CREATE USER pitboss WITH PASSWORD 'pitboss';
CREATE DATABASE pitboss;
ALTER DATABASE pitboss OWNER TO pitboss;

CREATE USER speedwager WITH PASSWORD 'speedwager';
CREATE DATABASE speedwager;
ALTER DATABASE speedwager OWNER TO speedwager;

CREATE USER sbp WITH PASSWORD 'sbp';
CREATE DATABASE sbp;
ALTER DATABASE sbp OWNER TO sbp;