-- defines the wager levels & currency sets
-- from 'Green Jade: Currencies and Bet Denominations | Slot Machine: Side Bet Proposed New'
-- UPDATED 10/29/2020 - to include "all" currencies - deployed to all production zones

delete from currencysets where id='gjg-2020';

-- fake testing currency
insert into currencysets (id, currency, multiplier) values ('gjg-2020', 'XTS', 1);

-- overrides for due to historical choices of the original gjg-2020:
insert into currencysets (id, currency, multiplier) values ('gjg-2020', 'PLN', 2);
insert into currencysets (id, currency, multiplier) values ('gjg-2020', 'RON', 2);
insert into currencysets (id, currency, multiplier) values ('gjg-2020', 'CNY', 4);
insert into currencysets (id, currency, multiplier) values ('gjg-2020', 'HRK', 5);
insert into currencysets (id, currency, multiplier) values ('gjg-2020', 'CZK', 10);
insert into currencysets (id, currency, multiplier) values ('gjg-2020', 'DKK', 10);
insert into currencysets (id, currency, multiplier) values ('gjg-2020', 'TRY', 10);     -- turkish lira 8/19/2020
insert into currencysets (id, currency, multiplier) values ('gjg-2020', 'THB', 20);
insert into currencysets (id, currency, multiplier) values ('gjg-2020', 'UAH', 20);
insert into currencysets (id, currency, multiplier) values ('gjg-2020', 'RUB', 100);    -- updated from 30:1 to 100:1 per Ben 8/25/2020
insert into currencysets (id, currency, multiplier) values ('gjg-2020', 'INR', 100);    -- indian rupies 6/19/2020
insert into currencysets (id, currency, multiplier) values ('gjg-2020', 'JPY', 100);
insert into currencysets (id, currency, multiplier, coinratio) values ('gjg-2020', 'VND', 10000, 100);
insert into currencysets (id, currency, multiplier) values ('gjg-2020', 'BRL', 5);      -- added 8/27/2020 per Ben
insert into currencysets (id, currency, multiplier) values ('gjg-2020', 'HUF', 350);    -- added 8/27/2020 per Ben
insert into currencysets (id, currency, multiplier) values ('gjg-2020', 'ZAR', 20);     -- added 8/27/2020 per Ben
insert into currencysets (id, currency, multiplier) values ('gjg-2020', 'CLP', 1000);   -- added 8/27/2020 per Ben

-- these are all auto-generated from a simple query against the same source that Cage uses with a spreadsheet to adjust them to whole rational multipliers:
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'KWD', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'BHD', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'OMR', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'LVL', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'JOD', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'FKP', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'GGP', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'GIP', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'IMP', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'JEP', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'SHP', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'GBP', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'KYD', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'EUR', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'CHF', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'BMD', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'CUC', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'USD', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'BSD', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'PAB', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'CAD', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'SGD', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'AUD', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'BND', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'LYD', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'NZD', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'BGN', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'BAM', 1) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'AZN', 2) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'ANG', 2) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'AWG', 2) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'BBD', 2) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'BZD', 2) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'FJD', 2) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'TOP', 2) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'WST', 3) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'BYN', 3) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'XCD', 3) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'TND', 3) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'LTL', 3) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'GEL', 3) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'ILS', 4) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'PGK', 4) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'TMT', 4) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'PEN', 4) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'QAR', 4) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'AED', 4) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'PLN', 4) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'SAR', 4) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'RON', 4) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'MYR', 4) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'BRL', 6) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'GHS', 6) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'DKK', 7) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'HRK', 7) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'TTD', 8) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'CNY', 8) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'BOB', 8) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'TRY', 8) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'SRD', 8) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'GTQ', 9) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'HKD', 9) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'MOP', 9) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'SBD', 9) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'SEK', 10) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'SVC', 10) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'NOK', 10) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'MAD', 10) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'VEF', 10) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'TJS', 10) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'BWP', 10) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'ERN', 10) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'MVR', 10) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'EGP', 10) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'ZAR', 10) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'MDL', 10) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'SZL', 10) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'LSL', 20) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'NAD', 20) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'SCR', 20) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'ZMW', 20) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'MXN', 20) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'CZK', 20) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'HNL', 20) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'CUP', 30) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'UAH', 30) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'TWD', 30) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'THB', 30) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'NIO', 40) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'ETB', 40) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'MUR', 40) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'UYU', 50) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'PHP', 50) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'MKD', 60) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'GMD', 60) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'SDG', 60) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'DOP', 60) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'MZN', 80) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'INR', 80) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'BTN', 80) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'ARS', 80) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'RUB', 80) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'AFN', 90) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'KGS', 90) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'BDT', 100) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'CVE', 100) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'RSD', 100) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'XPF', 100) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'ALL', 100) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'JPY', 100) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'KES', 100) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'HTG', 100) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'VUV', 100) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'NPR', 100) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'DZD', 100) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'ISK', 100) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'JMD', 100) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'PKR', 100) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'DJF', 200) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'LKR', 200) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'LRD', 200) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'GYD', 200) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'YER', 200) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'HUF', 300) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'ZWL', 300) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'MRO', 400) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'NGN', 400) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'KMF', 400) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'KZT', 500) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'AMD', 500) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'SYP', 600) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'XOF', 600) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'XAF', 600) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'SOS', 600) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'CRC', 700) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'AOA', 700) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'MWK', 800) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'CLP', 900) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'KPW', 1000) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'RWF', 1000) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'KRW', 1000) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'IQD', 1000) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'MMK', 1000) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'LBP', 1000) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'BIF', 2000) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'CDF', 2000) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'TZS', 2000) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'MNT', 3000) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'UGX', 4000) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'COP', 4000) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'MGA', 4000) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'KHR', 4000) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'PYG', 8000) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'ZMK', 10000) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'LAK', 10000) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'GNF', 10000) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'SLL', 10000) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'UZS', 10000) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'IDR', 10000) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'BYR', 20000) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'STD', 20000) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'VND', 20000) ON CONFLICT DO NOTHING;
INSERT INTO currencysets (id, currency, multiplier) VALUES ('gjg-2020', 'IRR', 50000) ON CONFLICT DO NOTHING;
